; nlib.inc

.globalzp _nl_sp, _nl_fp
.globalzp _nl_size, _nl_shift
.globalzp _nl_ptr1, _nl_ptr2, _nl_ptr3, _nl_ptr4
.globalzp _nl_tmp1, _nl_tmp2, _nl_tmp3, _nl_tmp4, _nl_tmp5, _nl_tmp6

; aliases because we hate typing
sp    = _nl_sp    ; 2 byte
fp    = _nl_fp    ; 2 byte
size  = _nl_size  ; 1 byte
shift = _nl_shift ; 1 byte
ptr1  = _nl_ptr1  ; 2 byte
ptr2  = _nl_ptr2  ; 2 byte
ptr3  = _nl_ptr3  ; 2 byte
ptr4  = _nl_ptr4  ; 2 byte
tmp1  = _nl_tmp1  ; 1 byte
tmp2  = _nl_tmp2  ; 1 byte
tmp3  = _nl_tmp3  ; 1 byte
tmp4  = _nl_tmp4  ; 1 byte
tmp5  = _nl_tmp5  ; 1 byte
tmp6  = _nl_tmp6  ; 1 byte

