// opcode_data_by_value.h
// Sorted list of all 256 6502 opcodes, including undocumented ones

{"BRK", "impl", 0x00},
{"ORA", "(ind,X)", 0x01},
{"*KIL", "impl", 0x02},
{"*SLO", "(ind,X)", 0x03},
{"NOP", "zpg", 0x04},
{"ORA", "zpg", 0x05},
{"ASL", "zpg", 0x06},
{"*SLO", "zpg", 0x07},
{"PHP", "impl", 0x08},
{"ORA", "imm", 0x09},
{"ASL", "impl", 0x0A},
{"*ANC", "imm", 0x0B},
{"NOP", "abs", 0x0C},
{"ORA", "abs", 0x0D},
{"ASL", "abs", 0x0E},
{"*SLO", "abs", 0x0F},

{"BPL", "rel", 0x10},
{"ORA", "(ind),Y", 0x11},
{"*KIL", "impl", 0x12},
{"*SLO", "(ind),Y", 0x13},
{"NOP", "zpg,X", 0x14},
{"ORA", "zpg,X", 0x15},
{"ASL", "zpg,X", 0x16},
{"*SLO", "zpg,X", 0x17},
{"CLC", "impl", 0x18},
{"ORA", "abs,Y", 0x19},
{"NOP", "impl", 0x1A},
{"*SLO", "abs,Y", 0x1B},
{"NOP", "abs,X", 0x1C},
{"ORA", "abs,X", 0x1D},
{"ASL", "abs,X", 0x1E},
{"*SLO", "abs,X", 0x1F},

{"JSR", "abs", 0x20},
{"AND", "(ind,X)", 0x21},
{"*KIL", "impl", 0x22},
{"*RLA", "(ind,X)", 0x23},
{"BIT", "zpg", 0x24},
{"AND", "zpg", 0x25},
{"ROL", "zpg", 0x26},
{"*RLA", "zpg", 0x27},
{"PLP", "impl", 0x28},
{"AND", "imm", 0x29},
{"ROL", "impl", 0x2A},
{"*ANC", "imm", 0x2B},
{"BIT", "abs", 0x2C},
{"AND", "abs", 0x2D},
{"ROL", "abs", 0x2E},
{"*RLA", "abs", 0x2F},

{"BMI", "rel", 0x30},
{"AND", "(ind),Y", 0x31},
{"*KIL", "impl", 0x32},
{"*RLA", "(ind),Y", 0x33},
{"NOP", "zpg,X", 0x34},
{"AND", "zpg,X", 0x35},
{"ROL", "zpg,X", 0x36},
{"*RLA", "zpg,X", 0x37},
{"SEC", "impl", 0x38},
{"AND", "abs,Y", 0x39},
{"NOP", "impl", 0x3A},
{"*RLA", "abs,Y", 0x3B},
{"BIT", "abs,X", 0x3C},
{"AND", "abs,X", 0x3D},
{"ROL", "abs,X", 0x3E},
{"*RLA", "abs,X", 0x3F},

{"RTI", "impl", 0x40},
{"EOR", "(ind,X)", 0x41},
{"*KIL", "impl", 0x42},
{"*SRE", "(ind,X)", 0x43},
{"NOP", "zpg", 0x44},
{"EOR", "zpg", 0x45},
{"LSR", "zpg", 0x46},
{"*SRE", "zpg", 0x47},
{"PHA", "impl", 0x48},
{"EOR", "imm", 0x49},
{"LSR", "impl", 0x4A},
{"*ALR", "imm", 0x4B},
{"JMP", "abs", 0x4C},
{"EOR", "abs", 0x4D},
{"LSR", "abs", 0x4E},
{"*SRE", "abs", 0x4F},

{"BVC", "rel", 0x50},
{"EOR", "(ind),Y", 0x51},
{"*KIL", "impl", 0x52},
{"*SRE", "(ind),Y", 0x53},
{"NOP", "zpg,X", 0x54},
{"EOR", "zpg,X", 0x55},
{"LSR", "zpg,X", 0x56},
{"*SRE", "zpg,X", 0x57},
{"CLI", "impl", 0x58},
{"EOR", "abs,Y", 0x59},
{"NOP", "impl", 0x5A},
{"*SRE", "abs,Y", 0x5B},
{"NOP", "abs,X", 0x5C},
{"EOR", "abs,X", 0x5D},
{"LSR", "abs,X", 0x5E},
{"*SRE", "abs,X", 0x5F},

{"RTS", "impl", 0x60},
{"ADC", "(ind,X)", 0x61},
{"*KIL", "impl", 0x62},
{"*RRA", "(ind,X)", 0x63},
{"NOP", "zpg", 0x64},
{"ADC", "zpg", 0x65},
{"ROR", "zpg", 0x66},
{"*RRA", "zpg", 0x67},
{"PLA", "impl", 0x68},
{"ADC", "imm", 0x69},
{"ROR", "impl", 0x6A},
{"*ARR", "imm", 0x6B},
{"JMP", "ind", 0x6C},
{"ADC", "abs", 0x6D},
{"ROR", "abs", 0x6E},
{"*RRA", "abs", 0x6F},

{"BVS", "rel", 0x70},
{"ADC", "(ind),Y", 0x71},
{"*KIL", "impl", 0x72},
{"*RRA", "(ind),Y", 0x73},
{"NOP", "zpg,X", 0x74},
{"ADC", "zpg,X", 0x75},
{"ROR", "zpg,X", 0x76},
{"*RRA", "zpg,X", 0x77},
{"SEI", "impl", 0x78},
{"ADC", "abs,Y", 0x79},
{"NOP", "impl", 0x7A},
{"*RRA", "abs,Y", 0x7B},
{"NOP", "abs,X", 0x7C},
{"ADC", "abs,X", 0x7D},
{"ROR", "abs,X", 0x7E},
{"*RRA", "abs,X", 0x7F},

{"*NOP", "imm", 0x80},
{"STA", "(ind,X)", 0x81},
{"*NOP", "imm", 0x82},
{"*SAX", "(ind,X)", 0x83},
{"STY", "zpg", 0x84},
{"STA", "zpg", 0x85},
{"STX", "zpg", 0x86},
{"*SAX", "zpg", 0x87},
{"DEY", "impl", 0x88},
{"*NOP", "imm", 0x89},
{"TXA", "impl", 0x8A},
{"*XAA", "imm", 0x8B},
{"STY", "abs", 0x8C},
{"STA", "abs", 0x8D},
{"STX", "abs", 0x8E},
{"*SAX", "abs", 0x8F},

{"BCC", "rel", 0x90},
{"STA", "(ind),Y", 0x91},
{"*KIL", "impl", 0x92},
{"*AHX", "(ind),Y", 0x93},
{"STY", "zpg,X", 0x94},
{"STA", "zpg,X", 0x95},
{"STX", "zpg,Y", 0x96},
{"*SAX", "zpg,Y", 0x97},
{"TYA", "impl", 0x98},
{"STA", "abs,Y", 0x99},
{"TXS", "impl", 0x9A},
{"*TAS", "abs,Y", 0x9B},
{"SHY", "abs,X", 0x9C},
{"STA", "abs,X", 0x9D},
{"SHX", "abs,Y", 0x9E},
{"*AHX", "abs,Y", 0x9F},

{"LDY", "imm", 0xA0},
{"LDA", "(ind,X)", 0xA1},
{"LDX", "imm", 0xA2},
{"*LAX", "(ind,X)", 0xA3}, // undocumented
{"LDY", "zpg", 0xA4},
{"LDA", "zpg", 0xA5},
{"LDX", "zpg", 0xA6},
{"*LAX", "zpg", 0xA7}, // undocumented
{"TAY", "impl", 0xA8},
{"LDA", "imm", 0xA9},
{"TAX", "impl", 0xAA},
{"*LAX", "imm", 0xAB}, // undocumented
{"LDY", "abs", 0xAC},
{"LDA", "abs", 0xAD},
{"LDX", "abs", 0xAE},
{"*LAX", "abs", 0xAF}, // undocumented

{"BCS", "rel", 0xB0},
{"LDA", "(ind),Y", 0xB1},
{"*KIL", "impl", 0xB2}, // undocumented
{"*LAX", "(ind),Y", 0xB3}, // undocumented
{"LDY", "zpg,X", 0xB4},
{"LDA", "zpg,X", 0xB5},
{"LDX", "zpg,Y", 0xB6},
{"*LAX", "zpg,Y", 0xB7}, // undocumented
{"CLV", "impl", 0xB8},
{"LDA", "abs,Y", 0xB9},
{"TSX", "impl", 0xBA},
{"*LAS", "abs,Y", 0xBB}, // undocumented
{"LDY", "abs,X", 0xBC},
{"LDA", "abs,X", 0xBD},
{"LDX", "abs,Y", 0xBE},
{"*LAX", "abs,Y", 0xBF}, // undocumented

{"CPY", "imm", 0xC0},
{"CMP", "(ind,X)", 0xC1},
{"*KIL", "impl", 0xC2}, // undocumented
{"*DCP", "(ind,X)", 0xC3}, // undocumented
{"CPY", "zpg", 0xC4},
{"CMP", "zpg", 0xC5},
{"DEC", "zpg", 0xC6},
{"*DCP", "zpg", 0xC7}, // undocumented
{"INY", "impl", 0xC8},
{"CMP", "imm", 0xC9},
{"DEX", "impl", 0xCA},
{"*AXS", "imm", 0xCB}, // undocumented
{"CPY", "abs", 0xCC},
{"CMP", "abs", 0xCD},
{"DEC", "abs", 0xCE},
{"*DCP", "abs", 0xCF}, // undocumented

{"BNE", "rel", 0xD0},
{"CMP", "(ind),Y", 0xD1},
{"*KIL", "impl", 0xD2}, // undocumented
{"*DCP", "(ind),Y", 0xD3}, // undocumented
{"*NOP", "zpg,X", 0xD4}, // undocumented
{"CMP", "zpg,X", 0xD5},
{"DEC", "zpg,X", 0xD6},
{"*DCP", "zpg,X", 0xD7}, // undocumented
{"CLD", "impl", 0xD8},
{"CMP", "abs,Y", 0xD9},
{"NOP", "impl", 0xDA}, // undocumented
{"*DCP", "abs,Y", 0xDB}, // undocumented
{"*NOP", "abs,X", 0xDC}, // undocumented
{"CMP", "abs,X", 0xDD},
{"DEC", "abs,X", 0xDE},
{"*DCP", "abs,X", 0xDF}, // undocumented

{"CPX", "imm", 0xE0},
{"SBC", "(ind,X)", 0xE1},
{"*KIL", "impl", 0xE2}, // undocumented
{"*ISC", "(ind,X)", 0xE3}, // undocumented
{"CPX", "zpg", 0xE4},
{"SBC", "zpg", 0xE5},
{"INC", "zpg", 0xE6},
{"*ISC", "zpg", 0xE7}, // undocumented
{"INX", "impl", 0xE8},
{"SBC", "imm", 0xE9},
{"NOP", "impl", 0xEA},
{"*SBC", "imm", 0xEB}, // undocumented
{"CPX", "abs", 0xEC},
{"SBC", "abs", 0xED},
{"INC", "abs", 0xEE},
{"*ISC", "abs", 0xEF}, // undocumented

{"BEQ", "rel", 0xF0},
{"SBC", "(ind),Y", 0xF1},
{"*KIL", "impl", 0xF2}, // undocumented
{"*ISC", "(ind),Y", 0xF3}, // undocumented
{"*NOP", "zpg,X", 0xF4}, // undocumented
{"SBC", "zpg,X", 0xF5},
{"INC", "zpg,X", 0xF6},
{"*ISC", "zpg,X", 0xF7}, // undocumented
{"SED", "impl", 0xF8},
{"SBC", "abs,Y", 0xF9},
{"NOP", "impl", 0xFA}, // undocumented
{"*ISC", "abs,Y", 0xFB}, // undocumented
{"*NOP", "abs,X", 0xFC}, // undocumented
{"SBC", "abs,X", 0xFD},
{"INC", "abs,X", 0xFE},
{"*ISC", "abs,X", 0xFF} // undocumented
