#!/usr/bin/perl
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Path qw(make_path);
use File::Spec;
use FindBin;
use Math::BigInt;

sub usage {
   die "usage: $0 [--build DIR] <typename> <little|big> <size-bytes> <exp-bits>\n";
}

sub pow2s {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b);
   return $x->bstr();
}

sub all1s {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b);
   $x->bdec();
   return $x->bstr();
}

sub typed {
   my ($v, $t) = @_;
   return "$v`$t";
}

sub biass {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b - 1);
   $x->bdec();
   return $x->bstr();
}

my $build_dir;
if (@ARGV >= 2 && $ARGV[0] eq '--build') {
   shift @ARGV;
   $build_dir = shift @ARGV;
   usage() if !defined $build_dir || $build_dir eq '';
}

my ($typename, $endian, $size, $expbits) = @ARGV;
usage() if @ARGV != 4;
usage() if $endian ne 'little' && $endian ne 'big';
usage() if $size !~ /^\d+$/ || $size <= 0;
usage() if $expbits !~ /^\d+$/ || $expbits <= 0;

my $total = $size * 8;
die "$0: invalid layout\n" if 1 + $expbits >= $total;
die "$0: generated arithmetic currently supports sizes up to 8 bytes\n" if $size > 8;

my $mbits = $total - 1 - $expbits;
my $last = $size - 1;
my $wide_bytes = $size * 2;
my $san = $typename;
$san =~ s/[^A-Za-z0-9_]/_/g;
$san = "t_$san" if $san !~ /^[A-Za-z]/;
my $u = "nlf_${san}_u";
my $wu = "nlf_${san}_wide_u";
my $bits = "nlf_${san}_bits";
my $ov = "nlf_${san}_overlay";
my $vov = "nlf_${san}_value_overlay";
my $uov = "nlf_${san}_u_overlay";
my ($matht, $math_bytes);
if ($size <= 2) {
   $matht = 'int';
   $math_bytes = 2;
}
elsif ($size <= 4) {
   $matht = 'long';
   $math_bytes = 4;
}
else {
   $matht = 'longlong';
   $math_bytes = 8;
}
my $mov = "nlf_${san}_math_overlay";
my $wov = "nlf_${san}_wide_overlay";

my $ga = "nlf_${san}_a";
my $gb = "nlf_${san}_b";
my $gr = "nlf_${san}_r";
my $gt = "nlf_${san}_t";
my $gmant_u = "nlf_${san}_mant_u";
my $gsig_u = "nlf_${san}_sig_u";
my $gtmp_u = "nlf_${san}_tmp_u";
my $gmant_ll = "nlf_${san}_mant_ll";
my $gsig_ll = "nlf_${san}_sig_ll";
my $gtmp_ll = "nlf_${san}_tmp_ll";
my $gamag = "nlf_${san}_amag";
my $gbmag = "nlf_${san}_bmag";
my $gwide_a = "nlf_${san}_wide_a";
my $gwide_b = "nlf_${san}_wide_b";
my $gwide_p = "nlf_${san}_wide_p";
my $gwide_t = "nlf_${san}_wide_t";
my $gexp_a = "nlf_${san}_exp_a";
my $gexp_b = "nlf_${san}_exp_b";
my $gsign_out = "nlf_${san}_sign_out";
my $gsig_a = "nlf_${san}_sig_a";
my $gsig_b = "nlf_${san}_sig_b";
my $gsig_out = "nlf_${san}_sig_out";
my $gcmp = "nlf_${san}_cmp";
my $gunordered = "nlf_${san}_unordered";
my $add_impl = "nlf_${san}_add_impl";
my $cmp_impl = "nlf_${san}_cmp_impl";
my $mul_impl = "nlf_${san}_mul_impl";
my $div_impl = "nlf_${san}_div_impl";

my $ZERO = typed(0, $u);
my $ONE = typed(1, $u);
my $W_ZERO = typed(0, $wu);
my $W_ONE = typed(1, $wu);
my $W_TWO = typed(2, $wu);
my $W_HIDDEN_EXT = typed(pow2s($mbits + 3), $wu);
my $EXP_MAX = typed(all1s($expbits), $u);
my $NAN_PAYLOAD = typed($mbits > 1 ? pow2s($mbits - 1) : 1, $u);
my $M_ZERO = typed(0, $matht);
my $M_ONE = typed(1, $matht);
my $M_TWO = typed(2, $matht);
my $M_EIGHT = typed(8, $matht);
my $M_EXP_MAX = typed(all1s($expbits), $matht);
my $M_BIAS = typed(biass($expbits), $matht);
my $FRACMASK = typed(all1s($mbits), $u);
my $M_HIDDEN = typed(pow2s($mbits), $matht);
my $M_HIDDEN_EXT = typed(pow2s($mbits + 3), $matht);
my $M_CARRY = typed(pow2s($mbits + 1), $matht);

my $CMP_EQ = 0;
my $CMP_LT = 1;
my $CMP_GT = 2;

sub comment_header {
   return <<"HDR";
// generated by libraries/float/gen.pl
// typename: $typename
// endian: $endian
// size: $size
// expbits: $expbits
// implementation: manual SExMy arithmetic using bitfields and unions

HDR
}

sub load_code {
   my ($ovname, $valname, $iv) = @_;
   return "   $ovname.value := $valname;\n" if $endian eq 'little';
   return "   $vov $iv;\n   int ${ovname}_i;\n   $iv.value := $valname;\n   ${ovname}_i := 0;\n   while (${ovname}_i < $size) {\n      $ovname.bytes[${ovname}_i] := $iv.bytes[$last - ${ovname}_i];\n      ${ovname}_i++;\n   }\n";
}

sub store_code {
   my ($ovname, $vv) = @_;
   return "   return $ovname.value;\n" if $endian eq 'little';
   return "   $vov $vv;\n   int ${ovname}_o;\n   ${ovname}_o := 0;\n   while (${ovname}_o < $size) {\n      $vv.bytes[${ovname}_o] := $ovname.bytes[$last - ${ovname}_o];\n      ${ovname}_o++;\n   }\n   return $vv.value;\n";
}

sub to_ll_snippet {
   my ($dst, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $src;
";
}

sub from_ll_snippet {
   my ($dst, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $src;
";
}

sub ll_to_wide_snippet {
   my ($dstw, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dstw.v := $src;
";
}

sub wide_to_ll_snippet {
   my ($dst, $srcw, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $srcw.v;
";
}

sub mag_cmp_snippet {
   my ($dst, $lhs, $rhs, $indent) = @_;
   $indent //= '   ';
   my $s = "${indent}$dst := $CMP_EQ;\n";
   for (my $i = $last; $i >= 0; --$i) {
      my $l = "($lhs.bytes[$i] & 255)";
      my $r = "($rhs.bytes[$i] & 255)";
      if ($i == $last) {
         $l = "($l & 127)";
         $r = "($r & 127)";
      }
      $s .= "${indent}if ($dst == $CMP_EQ) {\n";
      $s .= "${indent}   if ($l < $r) { $dst := $CMP_LT; }\n";
      $s .= "${indent}   else { if ($l > $r) { $dst := $CMP_GT; } }\n";
      $s .= "${indent}}\n";
   }
   return $s;
}

sub pack_snippet {
   my ($sig, $exp, $sign, $out, $mant) = @_;
   return "      $out.raw := $ZERO;
"
      . "      if ($sig == $M_ZERO) {
"
      . "         $out.bits.sign := $sign;
"
      . "      }
"
      . "      else {
"
      . "         ${matht} low;
"
      . "         low := $sig & 7`$matht;
"
      . "         $mant := $sig / $M_EIGHT;
"
      . "         if ((low & 4`$matht) != $M_ZERO && (((low & 3`$matht) != $M_ZERO) || (($mant & $M_ONE) != $M_ZERO))) {
"
      . "            $mant++;
"
      . "         }
"
      . "         if ($mant >= $M_CARRY) {
"
      . "            $mant /= $M_TWO;
"
      . "            $exp++;
"
      . "         }
"
      . "         if ($exp >= $M_EXP_MAX) {
"
      . "            $out.bits.sign := $sign;
"
      . "            $out.bits.exponent := $EXP_MAX;
"
      . "            $out.bits.mantissa := $ZERO;
"
      . "         }
"
      . "         else {
"
      . "            $out.bits.sign := $sign;
"
      . "            if ($mant >= $M_HIDDEN) {
"
      . "               $out.bits.exponent := $exp;
"
      . "               $out.bits.mantissa := $mant & $FRACMASK;
"
      . "            }
"
      . "            else {
"
      . "               $out.bits.exponent := $ZERO;
"
      . "               $out.bits.mantissa := $mant;
"
      . "            }
"
      . "         }
"
      . "      }
";
}

sub base_runtime_block {
   my ($static_prefix, $vars) = @_;
   $vars //= {};

   my $need_ov = 0;
   for my $k (qw(ga gb gr)) {
      if ($vars->{$k}) { $need_ov = 1; last; }
   }
   my $need_wide = 0;
   for my $k (qw(gwide_a gwide_b gwide_p gwide_t)) {
      if ($vars->{$k}) { $need_wide = 1; last; }
   }

   my $s = '';
   $s .= "type $u { \$size:$size \$unsigned \$endian:little };
";
   $s .= "type $wu { \$size:$wide_bytes \$unsigned \$endian:little };

" if $need_wide;
   if ($need_ov) {
      $s .= "struct $bits {
";
      $s .= "   $u mantissa:$mbits;
";
      $s .= "   $u exponent:$expbits;
";
      $s .= "   $u sign:1;
";
      $s .= "};
";
      if ($endian eq 'little') {
         $s .= "union $ov {
";
         $s .= "   $typename value;
";
         $s .= "   $u raw;
";
         $s .= "   char bytes[$size];
";
         $s .= "   $bits bits;
";
         $s .= "};
";
      }
      else {
         $s .= "union $vov {
";
         $s .= "   $typename value;
";
         $s .= "   char bytes[$size];
";
         $s .= "};

";
         $s .= "union $ov {
";
         $s .= "   $u raw;
";
         $s .= "   char bytes[$size];
";
         $s .= "   $bits bits;
";
         $s .= "};
";
      }
   }
   if ($need_wide) {
      $s .= "union $wov {
";
      $s .= "   $wu v;
";
      $s .= "   char bytes[$wide_bytes];
";
      $s .= "};

";
   }

   my @decls;
   push @decls, "$ov $ga" if $vars->{ga};
   push @decls, "$ov $gb" if $vars->{gb};
   push @decls, "$ov $gr" if $vars->{gr};
   push @decls, "$wov $gwide_a" if $vars->{gwide_a};
   push @decls, "$wov $gwide_b" if $vars->{gwide_b};
   push @decls, "$wov $gwide_p" if $vars->{gwide_p};
   push @decls, "$wov $gwide_t" if $vars->{gwide_t};
   push @decls, "$matht $gmant_ll" if $vars->{gmant_ll};
   push @decls, "$matht $gexp_a" if $vars->{gexp_a};
   push @decls, "$matht $gexp_b" if $vars->{gexp_b};
   push @decls, "int $gsign_out" if $vars->{gsign_out};
   push @decls, "$matht $gsig_a" if $vars->{gsig_a};
   push @decls, "$matht $gsig_b" if $vars->{gsig_b};
   push @decls, "$matht $gsig_out" if $vars->{gsig_out};
   push @decls, "int $gcmp" if $vars->{gcmp};
   push @decls, "int $gunordered" if $vars->{gunordered};

   for my $decl (@decls) {
      $s .= "$static_prefix$decl;
";
   }
   $s .= "
";
   return $s;
}

sub add_impl_text {
   my ($static_prefix) = @_;
   my $s = "${static_prefix}void $add_impl(void) {\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $gb.bits.exponent == $EXP_MAX && $ga.bits.sign != $gb.bits.sign) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $ZERO;\n      $gr.bits.exponent := $EXP_MAX;\n      $gr.bits.mantissa := $NAN_PAYLOAD;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      if ($ga.bits.sign == $gb.bits.sign) { $gr.bits.sign := $ga.bits.sign; } else { $gr.bits.sign := $ZERO; }\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   $gsig_a := $ga.bits.mantissa;\n   $gsig_b := $gb.bits.mantissa;\n   $gexp_a := $ga.bits.exponent;\n   $gexp_b := $gb.bits.exponent;\n   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n   $gsig_a *= $M_EIGHT;\n   $gsig_b *= $M_EIGHT;\n   if ($ga.bits.sign == $gb.bits.sign) {\n      while ($gexp_a < $gexp_b) { $matht lost; lost := $gsig_a & $M_ONE; $gsig_a /= $M_TWO; if (lost != $M_ZERO) { $gsig_a |= $M_ONE; } $gexp_a++; }\n      while ($gexp_b < $gexp_a) { $matht lost; lost := $gsig_b & $M_ONE; $gsig_b /= $M_TWO; if (lost != $M_ZERO) { $gsig_b |= $M_ONE; } $gexp_b++; }\n      $gsig_out := $gsig_a + $gsig_b;\n      $gsign_out := $ga.bits.sign;\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "      return;\n   }\n";
   $s .= mag_cmp_snippet($gcmp, $ga, $gb, '   ');
   $s .= "   if ($gcmp == $CMP_EQ) { $gr.raw := $ZERO; return; }\n   if ($gcmp == $CMP_LT) {\n      $gr.raw := $ga.raw;\n      $ga.raw := $gb.raw;\n      $gb.raw := $gr.raw;\n      $gsig_a := $ga.bits.mantissa;\n      $gsig_b := $gb.bits.mantissa;\n      $gexp_a := $ga.bits.exponent;\n      $gexp_b := $gb.bits.exponent;\n      if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n      if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n      if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n      if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n      $gsig_a *= $M_EIGHT;\n      $gsig_b *= $M_EIGHT;\n   }\n   while ($gexp_a < $gexp_b) { $matht lost; lost := $gsig_a & $M_ONE; $gsig_a /= $M_TWO; if (lost != $M_ZERO) { $gsig_a |= $M_ONE; } $gexp_a++; }\n   while ($gexp_b < $gexp_a) { $matht lost; lost := $gsig_b & $M_ONE; $gsig_b /= $M_TWO; if (lost != $M_ZERO) { $gsig_b |= $M_ONE; } $gexp_b++; }\n   $gsig_out := $gsig_a - $gsig_b;\n   $gsign_out := $ga.bits.sign;\n   while ($gsig_out != $M_ZERO && $gexp_a > $M_ONE && $gsig_out < $M_HIDDEN_EXT) { $gsig_out *= $M_TWO; $gexp_a--; }\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}\n\n";
   return $s;
}

sub cmp_impl_text {
   my ($static_prefix) = @_;
   return "${static_prefix}void $cmp_impl(void) {\n   $gunordered := 0;\n   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) { $gunordered := 1; $gcmp := 0; return; }\n   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) { $gunordered := 1; $gcmp := 0; return; }\n   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) { $gcmp := 0; return; }\n   if ($ga.bits.sign != $gb.bits.sign) { if ($ga.bits.sign != $ZERO) { $gcmp := $CMP_LT; } else { $gcmp := $CMP_GT; } return; }\n"
      . mag_cmp_snippet($gcmp, $ga, $gb, '   ')
      . "   if ($ga.bits.sign != $ZERO) { if ($gcmp == $CMP_LT) { $gcmp := $CMP_GT; } else { if ($gcmp == $CMP_GT) { $gcmp := $CMP_LT; } } }\n}\n\n";
}

sub mul_impl_text {
   my ($static_prefix) = @_;
   my $s = "${static_prefix}void $mul_impl(void) {\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;\n";
   $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) || ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO && $ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO)) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $ZERO;\n      $gr.bits.exponent := $EXP_MAX;\n      $gr.bits.mantissa := $NAN_PAYLOAD;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      $gr.bits.exponent := $EXP_MAX;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      $gr.bits.exponent := $EXP_MAX;\n      return;\n   }\n";
   $s .= "   if (($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) || ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      return;\n   }\n";
   $s .= "   $gsig_a := $ga.bits.mantissa;\n   $gsig_b := $gb.bits.mantissa;\n   $gexp_a := $ga.bits.exponent;\n   $gexp_b := $gb.bits.exponent;\n   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n   $gexp_a := $gexp_a + $gexp_b - $M_BIAS;\n   $gwide_a.v := $gsig_a;\n   $gwide_b.v := $gsig_b;\n   $gwide_p.v := $gwide_a.v * $gwide_b.v;\n";
   if ($mbits > 3) {
      my $shift = $mbits - 3;
      $s .= "   $gwide_t.v := $gwide_p.v >> $shift;\n";
      $s .= "   $gwide_a.v := $gwide_t.v << $shift;\n";
      $s .= "   if ($gwide_a.v != $gwide_p.v) { $gwide_t.v |= $W_ONE; }\n";
      $s .= "   $gwide_p.v := $gwide_t.v;\n";
   }
   elsif ($mbits < 3) {
      my $shift = 3 - $mbits;
      $s .= "   $gwide_p.v := $gwide_p.v << $shift;\n";
   }
   $s .= "   $gsig_out := $gwide_p.v;\n";
   $s .= "   while ($gsig_out != $M_ZERO && $gexp_a > $M_ONE && $gsig_out < $M_HIDDEN_EXT) { $gsig_out *= $M_TWO; $gexp_a--; }\n";
   $s .= "   while ($gsig_out != $M_ZERO && $gexp_a < $M_ONE) { $matht lost; lost := $gsig_out & $M_ONE; $gsig_out /= $M_TWO; if (lost != $M_ZERO) { $gsig_out |= $M_ONE; } $gexp_a++; }\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}\n\n";
   return $s;
}

sub div_impl_text {
   my ($static_prefix) = @_;
   my $s = "${static_prefix}void $div_impl(void) {\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;\n";
   $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) || ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $ZERO;\n      $gr.bits.exponent := $EXP_MAX;\n      $gr.bits.mantissa := $NAN_PAYLOAD;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      $gr.bits.exponent := $EXP_MAX;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      $gr.bits.exponent := $EXP_MAX;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $gsign_out;\n      return;\n   }\n";
   $s .= "   $gsig_a := $ga.bits.mantissa;\n   $gsig_b := $gb.bits.mantissa;\n   $gexp_a := $ga.bits.exponent;\n   $gexp_b := $gb.bits.exponent;\n   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n   $gexp_a := $gexp_a - $gexp_b + $M_BIAS;\n   $gwide_a.v := $gsig_a;\n   $gwide_a.v := $gwide_a.v << @{[$mbits + 3]};\n   $gwide_b.v := $gsig_b;\n   $gwide_p.v := $gwide_a.v / $gwide_b.v;\n   $gwide_t.v := $gwide_p.v * $gwide_b.v;\n   if ($gwide_t.v != $gwide_a.v) { $gwide_p.v |= $W_ONE; }\n";
   $s .= "   while ($gwide_p.v != $W_ZERO && $gexp_a > $M_ONE && $gwide_p.v < $W_HIDDEN_EXT) { $gwide_p.v := $gwide_p.v << 1; $gexp_a--; }\n";
   $s .= "   while ($gwide_p.v != $W_ZERO && $gexp_a < $M_ONE) { $gwide_t.v := $gwide_p.v & $W_ONE; $gwide_p.v := $gwide_p.v >> 1; if ($gwide_t.v != $W_ZERO) { $gwide_p.v |= $W_ONE; } $gexp_a++; }\n";
   $s .= "   $gsig_out := $gwide_p.v;\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}\n\n";
   return $s;
}

sub operator_add_text {
   my $s = "$typename operator+($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $add_impl();\n";
   $s .= store_code($gr, 'rv');
   $s .= "}\n\n";
   return $s;
}

sub operator_sub_text {
   my $s = "$typename operator-($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $gb.bits.sign ^= $ONE;\n   $add_impl();\n";
   $s .= store_code($gr, 'rv');
   $s .= "}\n\n";
   return $s;
}

sub operator_mul_text {
   my $s = "$typename operator*($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $mul_impl();\n";
   $s .= store_code($gr, 'rv');
   $s .= "}\n\n";
   return $s;
}

sub operator_div_text {
   my $s = "$typename operator/($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $div_impl();\n";
   $s .= store_code($gr, 'rv');
   $s .= "}\n\n";
   return $s;
}

sub operator_eq_text {
   my $s = "bool operator==($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 0`bool; }\n   if ($gcmp == $CMP_EQ) { return 1`bool; }\n   return 0`bool;\n}\n\n";
   return $s;
}

sub operator_ne_text {
   my $s = "bool operator!=($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 1`bool; }\n   if ($gcmp != $CMP_EQ) { return 1`bool; }\n   return 0`bool;\n}\n\n";
   return $s;
}

sub operator_lt_text {
   my $s = "bool operator<($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 0`bool; }\n   if ($gcmp == $CMP_LT) { return 1`bool; }\n   return 0`bool;\n}\n\n";
   return $s;
}

sub operator_gt_text {
   my $s = "bool operator>($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 0`bool; }\n   if ($gcmp == $CMP_GT) { return 1`bool; }\n   return 0`bool;\n}\n\n";
   return $s;
}

sub operator_le_text {
   my $s = "bool operator<=($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 0`bool; }\n   if ($gcmp != $CMP_GT) { return 1`bool; }\n   return 0`bool;\n}\n\n";
   return $s;
}

sub operator_ge_text {
   my $s = "bool operator>=($typename lhs, $typename rhs) {\n";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();\n   if ($gunordered != 0) { return 0`bool; }\n   if ($gcmp != $CMP_LT) { return 1`bool; }\n   return 0`bool;\n}\n";
   return $s;
}

sub monolith_text {
   return comment_header()
      . base_runtime_block('', {
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1, gunordered => 1,
      })
      . add_impl_text('')
      . cmp_impl_text('')
      . mul_impl_text('')
      . div_impl_text('')
      . operator_add_text()
      . operator_sub_text()
      . operator_mul_text()
      . operator_div_text()
      . operator_eq_text()
      . operator_ne_text()
      . operator_lt_text()
      . operator_gt_text()
      . operator_le_text()
      . operator_ge_text();
}

sub ieee754_expbits_for_size {
   my ($n) = @_;
   return 5 if $n == 2;
   return 8 if $n == 4;
   return 11 if $n == 8;
   return -1;
}

sub simple_expbits_for_size {
   my ($n) = @_;
   return -1 if $n <= 0;
   my $bits = $n * 8;
   my $raw = 3.0 * (log($n) / log(2.0)) + 2.0;
   my $eb = int($raw + 0.5);
   $eb = 1 if $eb < 1;
   $eb = $bits - 2 if 1 + $eb >= $bits;
   return $eb > 0 ? $eb : -1;
}

sub inferred_float_style {
   return 'ieee754' if $expbits == ieee754_expbits_for_size($size);
   return 'simple' if $expbits == simple_expbits_for_size($size);
   return undef;
}

sub decls_text {
   my $style = inferred_float_style();
   my $s = comment_header();
   if ($style) {
      $s .= "type $typename { \$size:$size \$endian:$endian \$float:$style };\n\n";
   }
   else {
      $s .= "// note: could not infer a built-in \$float: style for expbits=$expbits; the generated declaration uses only size/endian\n";
      $s .= "type $typename { \$size:$size \$endian:$endian };\n\n";
   }
   $s .= "extern $typename operator+($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator-($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator*($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator/($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator==($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator!=($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator<($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator>($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator<=($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator>=($typename lhs, $typename rhs);\n";
   return $s;
}

sub standalone_prelude {
   my $style = inferred_float_style();
   my $s = <<"PRELUDE";
type void     { \$size:0 };
type char     { \$size:1 };
type bool     { \$size:1 };
type *        { \$size:2 \$endian:little };
type int      { \$size:2 \$endian:little };
type long     { \$size:4 \$endian:little };
type longlong { \$size:8 \$endian:little };
PRELUDE
   if ($style) {
      $s .= "type $typename { \$size:$size \$endian:$endian \$float:$style };
";
   }
   else {
      $s .= "type $typename { \$size:$size \$endian:$endian };
";
   }
   $s .= "
";
   return $s;
}

my %build_ops = (
   add => {
      source_name => "${typename}_operator_add.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gr => 1, gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1 }) . add_impl_text('static ') . operator_add_text(); },
   },
   sub => {
      source_name => "${typename}_operator_sub.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gr => 1, gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1 }) . add_impl_text('static ') . operator_sub_text(); },
   },
   mul => {
      source_name => "${typename}_operator_mul.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gr => 1, gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1, gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1 }) . mul_impl_text('static ') . operator_mul_text(); },
   },
   div => {
      source_name => "${typename}_operator_div.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gr => 1, gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1, gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1 }) . div_impl_text('static ') . operator_div_text(); },
   },
   eq => {
      source_name => "${typename}_operator_eq.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_eq_text(); },
   },
   ne => {
      source_name => "${typename}_operator_ne.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_ne_text(); },
   },
   lt => {
      source_name => "${typename}_operator_lt.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_lt_text(); },
   },
   gt => {
      source_name => "${typename}_operator_gt.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_gt_text(); },
   },
   le => {
      source_name => "${typename}_operator_le.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_le_text(); },
   },
   ge => {
      source_name => "${typename}_operator_ge.n",
      source_text => sub { return comment_header() . standalone_prelude() . base_runtime_block('static ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }) . cmp_impl_text('static ') . operator_ge_text(); },
   },
);

sub run_checked {
   my (@cmd) = @_;
   system(@cmd);
   if ($? != 0) {
      my $ec = $? >> 8;
      my $sig = $? & 127;
      die "$0: command failed (exit=$ec signal=$sig): @cmd\n";
   }
}

sub build_mode {
   my $out_dir = File::Spec->rel2abs($build_dir);
   my $repo_root = abs_path(File::Spec->catdir($FindBin::RealBin, '..', '..'));
   my $n65cc = $ENV{N65CC} || File::Spec->catfile($repo_root, 'compiler', 'n65cc');
   my $n65asm = $ENV{N65ASM} || File::Spec->catfile($repo_root, 'assembler', 'n65asm');
   my $n65ar = $ENV{N65AR} || File::Spec->catfile($repo_root, 'archiver', 'n65ar');
   my $nlib_inc = File::Spec->catdir($repo_root, 'libraries', 'nlib');

   for my $tool ($n65cc, $n65asm, $n65ar) {
      die "$0: required tool not found: $tool\n" if !-x $tool;
   }
   die "$0: required include dir not found: $nlib_inc\n" if !-d $nlib_inc;

   make_path($out_dir) if !-d $out_dir;

   my $decls_path = File::Spec->catfile($out_dir, "${typename}_decls.n");
   open(my $dfh, '>', $decls_path) or die "$0: could not write $decls_path: $!\n";
   print $dfh decls_text();
   close($dfh);

   my @member_objects;
   for my $key (qw(add sub mul div eq ne lt gt le ge)) {
      my $src_name = $build_ops{$key}->{source_name};
      my $src_path = File::Spec->catfile($out_dir, $src_name);
      my ($stem) = $src_name =~ /^(.*)\.n$/;
      my $s_path = File::Spec->catfile($out_dir, "$stem.s");
      my $o_path = File::Spec->catfile($out_dir, "$stem.o65");

      open(my $sfh, '>', $src_path) or die "$0: could not write $src_path: $!\n";
      print $sfh $build_ops{$key}->{source_text}->();
      close($sfh);

      run_checked($n65cc, '-quiet', $src_path, '-o', $s_path);
      run_checked($n65asm, '-I', $nlib_inc, '-o', $o_path, $s_path);
      push @member_objects, $o_path;
   }

   my $archive_path = File::Spec->catfile($out_dir, "${typename}.a65");
   run_checked($n65ar, 'rcs', $archive_path, @member_objects);
}

if (defined $build_dir) {
   build_mode();
}
else {
   print monolith_text();
}
