#!/usr/bin/perl
use strict;
use warnings;

sub mangle_text {
   my ($text) = @_;
   my $out = '';
   foreach my $c (split //, $text) {
      if ($c =~ /[A-Za-z0-9]/) {
         $out .= $c;
      }
      else {
         $out .= sprintf('x%02X', ord($c));
      }
   }
   return $out;
}

sub sym {
   my ($op, @types) = @_;
   my $s = mangle_text("operator$op");
   foreach my $t (@types) {
      $s .= '__' . mangle_text($t) . '_p0_a0';
   }
   return $s;
}

sub emit_prologue {
   print "    lda sp+1\n";
   print "    sta fp+1\n";
   print "    lda sp\n";
   print "    sta fp\n";
}

sub emit_ptr {
   my ($ptrn, $off) = @_;
   print "    lda #\$$off\n";
   print "    sta arg0\n";
   print "    jsr _fp2ptr${ptrn}m\n";
}

sub emit_ptrp {
   my ($ptrn, $off) = @_;
   print "    lda #\$$off\n";
   print "    sta arg0\n";
   print "    jsr _fp2ptr${ptrn}p\n";
}

sub emit_rts { print "    rts\n"; }

sub emit_zero_ret {
   my ($ret_off, $size, $ptrn) = @_;
   emit_ptr($ptrn, sprintf('%02x', $ret_off));
   print "    ldy #0\n";
   print "\@zero_loop:\n";
   print "    lda #0\n";
   print "    sta (ptr$ptrn),y\n";
   print "    iny\n";
   print "    cpy #\$$size\n";
   print "    bne \@zero_loop\n";
}

my @types;
push @types, ['int', 2, 0], ['long', 4, 0], ['longlong', 8, 0], ['char', 1, 0], ['bool', 1, 0];
for my $n (1..16) {
   push @types, ["s$n", $n, 1], ["u$n", $n, 0];
}
my @floats = (['half',2], ['float',4], ['double',8]);

open my $fh, '>', 'asm/weakops.asm' or die $!;
select $fh;
print ";;; generated by libraries/nlib/gen_weakops.pl\n";
print ".include \"nlib.inc\"\n\n";

for my $t (@types) {
   my ($name, $size, $signed) = @$t;
   my $arg1 = $size;
   my $arg2 = $size * 2;
   my $ret  = $size * 3;
   my $uarg = $size;
   my $uret = $size * 2;
   my $cmp_ret = $size * 2 + 1;
   my $cmp_lhs = $size;
   my $cmp_rhs = $size * 2;
   my @bin_same = (
      ['+', 'addN'], ['-', 'subN'], ['&', 'bit_andN'], ['|', 'bit_orN'], ['^', 'bit_xorN']
   );
   for my $pair (@bin_same) {
      my ($op, $helper) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      emit_ptr(2, sprintf('%02x', $ret));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      emit_rts();
      print ".endproc\n\n";
   }
   {
      my $sym = sym('*', $name, $name);
      my $scratch = $size * 2;
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _pushN\n";
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      emit_ptrp(2, sprintf('%02x', 0));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _mulN\n";
      emit_ptrp(0, sprintf('%02x', 0));
      emit_ptr(1, sprintf('%02x', $ret));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _cpyN\n";
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _popN\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (['/', 0], ['%', 1]) {
      my ($op, $want_rem) = @$pair;
      my $sym = sym($op, $name, $name);
      my $scratch = $size * 2;
      my $quo = 0;
      my $rem = $size;
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _pushN\n";
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      emit_ptrp(2, sprintf('%02x', $quo));
      emit_ptrp(3, sprintf('%02x', $rem));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _divN\n";
      emit_ptrp(0, sprintf('%02x', $want_rem ? $rem : $quo));
      emit_ptr(1, sprintf('%02x', $ret));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _cpyN\n";
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _popN\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (['<<', 'lslN'], ['>>', $signed ? 'asrN' : 'lsrN']) {
      my ($op, $helper) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $ret));
      emit_ptr(2, sprintf('%02x', $arg2));
      print "    ldy #0\n";
      print "    lda (ptr2),y\n";
      print "    sta arg1\n";
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (
      ['==', 'eqN', 0], ['!=', 'eqN', 1],
      ['<',  $signed ? 'ltNs' : 'ltNu', 0],
      ['<=', $signed ? 'leNs' : 'leNu', 0],
      ['>',  $signed ? 'ltNs' : 'ltNu', 2],
      ['>=', $signed ? 'leNs' : 'leNu', 2]
   ) {
      my ($op, $helper, $mode) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      if ($mode && $mode == 2) {
         emit_ptr(0, sprintf('%02x', $cmp_rhs));
         emit_ptr(1, sprintf('%02x', $cmp_lhs));
      }
      else {
         emit_ptr(0, sprintf('%02x', $cmp_lhs));
         emit_ptr(1, sprintf('%02x', $cmp_rhs));
      }
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      if ($mode && $mode == 1) {
         print "    lda arg1\n";
         print "    eor #1\n";
         print "    sta arg1\n";
      }
      emit_ptr(2, sprintf('%02x', $cmp_ret));
      print "    ldy #0\n";
      print "    lda arg1\n";
      print "    sta (ptr2),y\n";
      emit_rts();
      print ".endproc\n\n";
   }
   my $usym = sym('-', $name);
   print ".weak $usym\n.proc $usym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(1, sprintf('%02x', $uret));
   print "    lda #\$" . sprintf('%02x', $size) . "\n";
   print "    sta arg0\n";
   print "    jsr _comp2N\n";
   emit_rts();
   print ".endproc\n\n";

   my $tsym = sym('~', $name);
   print ".weak $tsym\n.proc $tsym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(2, sprintf('%02x', $uret));
   print "    lda #\$" . sprintf('%02x', $size) . "\n";
   print "    sta arg0\n";
   print "    jsr _bit_notN\n";
   emit_rts();
   print ".endproc\n\n";
}

for my $t (@floats) {
   my ($name, $size) = @$t;
   my $expbits = $name eq 'half' ? 5 : ($name eq 'double' ? 11 : 8);
   my $arg1 = $size;
   my $arg2 = $size * 2;
   my $ret  = $size * 3;
   my $uarg = $size;
   my $uret = $size * 2;
   my $cmp_ret = 1 + $size * 2;

   for my $pair (['+', '_faddN'], ['-', '_fsubN'], ['*', '_fmulN'], ['/', '_fdivN']) {
      my ($op, $helper) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      emit_ptr(2, sprintf('%02x', $ret));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    lda #\$" . sprintf('%02x', $expbits) . "\n";
      print "    sta arg1\n";
      print "    jsr $helper\n";
      emit_rts();
      print ".endproc\n\n";
   }

   for my $op ('==', '!=', '<', '<=', '>', '>=') {
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    lda #\$" . sprintf('%02x', $expbits) . "\n";
      print "    sta arg1\n";
      print "    jsr _fcmp\n";
      emit_ptr(2, sprintf('%02x', $cmp_ret));
      print "    ldy #0\n";
      if ($op eq '==') {
         print "    lda arg1\n";
         print "    beq \@true\n";
      }
      elsif ($op eq '!=') {
         print "    lda arg1\n";
         print "    bne \@true\n";
      }
      elsif ($op eq '<') {
         print "    lda arg1\n";
         print "    cmp #\$ff\n";
         print "    beq \@true\n";
      }
      elsif ($op eq '<=') {
         print "    lda arg1\n";
         print "    cmp #\$01\n";
         print "    bne \@true\n";
      }
      elsif ($op eq '>') {
         print "    lda arg1\n";
         print "    cmp #\$01\n";
         print "    beq \@true\n";
      }
      else {
         print "    lda arg1\n";
         print "    cmp #\$ff\n";
         print "    bne \@true\n";
      }
      print "    lda #0\n";
      print "    beq \@store\n";
      print "\@true:\n";
      print "    lda #1\n";
      print "\@store:\n";
      print "    sta (ptr2),y\n";
      emit_rts();
      print ".endproc\n\n";
   }

   my $usym = sym('-', $name);
   print ".weak $usym\n.proc $usym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(1, sprintf('%02x', $uret));
   print "    ldy #0\n";
   print "\@copy_loop:\n";
   print "    lda (ptr0),y\n";
   print "    sta (ptr1),y\n";
   print "    iny\n";
   print "    cpy #\$" . sprintf('%02x', $size) . "\n";
   print "    bne \@copy_loop\n";
   print "    ldy #\$" . sprintf('%02x', $size - 1) . "\n";
   print "    lda (ptr1),y\n";
   print "    eor #\$80\n";
   print "    sta (ptr1),y\n";
   emit_rts();
   print ".endproc\n\n";
}
